{{- if .Values.admissionWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "potoo.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "potoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "potoo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
{{- end }}
